export interface Article {
  slug: string;
  category: "prix" | "guide" | "conseil" | "normes" | "tendance";
  readTime: number;
  datePublished: string;
  dateModified: string;
  featuredImage: string;
  relatedSlugs?: string[];
  relatedServices?: string[];
}

export const ARTICLES: Article[] = [
  {
    slug: "prix-renovation-salle-de-bain-saint-louis",
    category: "prix",
    readTime: 7,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/prix-renovation-salle-de-bain-saint-louis.webp",
    relatedSlugs: ["cout-cuisine-equipee-alsace", "renovation-appartement-bale-demarches"],
    relatedServices: ["salle-de-bain", "plomberie"],
  },
  {
    slug: "cout-cuisine-equipee-alsace",
    category: "prix",
    readTime: 8,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/cout-cuisine-equipee-alsace.webp",
    relatedSlugs: ["prix-renovation-salle-de-bain-saint-louis", "renover-maison-ancienne-saint-louis"],
    relatedServices: ["cuisine", "sols-carrelage"],
  },
  {
    slug: "renovation-appartement-bale-demarches",
    category: "guide",
    readTime: 9,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/renovation-appartement-bale-demarches.webp",
    relatedSlugs: ["artisan-frontalier-france-suisse-avantages", "choisir-artisan-renovation-10-criteres"],
    relatedServices: ["renovation-complete", "electricite"],
  },
  {
    slug: "artisan-frontalier-france-suisse-avantages",
    category: "conseil",
    readTime: 6,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/artisan-frontalier-france-suisse-avantages.webp",
    relatedSlugs: ["renovation-appartement-bale-demarches", "choisir-artisan-renovation-10-criteres"],
    relatedServices: ["renovation-complete", "depannage-urgence"],
  },
  {
    slug: "isolation-thermique-haut-rhin-primes-2026",
    category: "normes",
    readTime: 8,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/isolation-thermique-haut-rhin-primes-2026.webp",
    relatedSlugs: ["renovation-energetique-aides-2026", "renover-maison-ancienne-saint-louis"],
    relatedServices: ["isolation", "facade"],
  },
  {
    slug: "renover-maison-ancienne-saint-louis",
    category: "guide",
    readTime: 10,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/renover-maison-ancienne-saint-louis.webp",
    relatedSlugs: ["isolation-thermique-haut-rhin-primes-2026", "renovation-energetique-aides-2026"],
    relatedServices: ["renovation-complete", "isolation", "facade"],
  },
  {
    slug: "carrelage-ou-parquet-guide-alsace",
    category: "guide",
    readTime: 6,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/carrelage-ou-parquet-guide-alsace.webp",
    relatedSlugs: ["prix-renovation-salle-de-bain-saint-louis", "cout-cuisine-equipee-alsace"],
    relatedServices: ["sols-carrelage"],
  },
  {
    slug: "peinture-interieure-mulhouse-tendances",
    category: "tendance",
    readTime: 5,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/peinture-interieure-mulhouse-tendances.webp",
    relatedSlugs: ["carrelage-ou-parquet-guide-alsace", "renovation-loft-mulhouse-idees"],
    relatedServices: ["peinture"],
  },
  {
    slug: "electricite-normes-nf-c-15-100",
    category: "normes",
    readTime: 7,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/electricite-normes-nf-c-15-100.webp",
    relatedSlugs: ["plomberie-renovation-signes-refaire", "renovation-appartement-bale-demarches"],
    relatedServices: ["electricite", "borne-recharge"],
  },
  {
    slug: "plomberie-renovation-signes-refaire",
    category: "conseil",
    readTime: 6,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/plomberie-renovation-signes-refaire.webp",
    relatedSlugs: ["electricite-normes-nf-c-15-100", "prix-renovation-salle-de-bain-saint-louis"],
    relatedServices: ["plomberie", "depannage-urgence"],
  },
  {
    slug: "ravalement-facade-haut-rhin-prix",
    category: "prix",
    readTime: 7,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/ravalement-facade-haut-rhin-prix.webp",
    relatedSlugs: ["isolation-thermique-haut-rhin-primes-2026", "renover-maison-ancienne-saint-louis"],
    relatedServices: ["facade", "peinture"],
  },
  {
    slug: "renovation-energetique-aides-2026",
    category: "normes",
    readTime: 9,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/renovation-energetique-aides-2026.webp",
    relatedSlugs: ["isolation-thermique-haut-rhin-primes-2026", "renover-maison-ancienne-saint-louis"],
    relatedServices: ["isolation", "panneaux-photovoltaiques"],
  },
  {
    slug: "salle-de-bain-pmr-seniors-guide",
    category: "guide",
    readTime: 7,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/salle-de-bain-pmr-seniors-guide.webp",
    relatedSlugs: ["prix-renovation-salle-de-bain-saint-louis", "electricite-normes-nf-c-15-100"],
    relatedServices: ["salle-de-bain", "plomberie", "electricite"],
  },
  {
    slug: "renovation-loft-mulhouse-idees",
    category: "tendance",
    readTime: 6,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/renovation-loft-mulhouse-idees.webp",
    relatedSlugs: ["peinture-interieure-mulhouse-tendances", "carrelage-ou-parquet-guide-alsace"],
    relatedServices: ["renovation-complete", "sols-carrelage", "peinture"],
  },
  {
    slug: "choisir-artisan-renovation-10-criteres",
    category: "conseil",
    readTime: 5,
    datePublished: "2026-04-07",
    dateModified: "2026-04-07",
    featuredImage: "/images/blog/choisir-artisan-renovation-10-criteres.webp",
    relatedSlugs: ["artisan-frontalier-france-suisse-avantages", "renovation-appartement-bale-demarches"],
    relatedServices: ["renovation-complete", "depannage-urgence"],
  },
];
