export interface VilleFR {
  slug: string;
  name: string;
  codePostal: string;
  population?: number;
  distance: number; // km depuis Saint-Louis
  featuredImage: string;
  specificites: string[]; // 3-5 points uniques (histoire, architecture, économie)
  communesAlentours: string[];
  seoTitle: string;
  seoDescription: string;
}

export const VILLES_FR: VilleFR[] = [
  {
    slug: "saint-louis",
    name: "Saint-Louis",
    codePostal: "68300",
    population: 21000,
    distance: 0,
    featuredImage: "/images/villes/saint-louis.webp",
    specificites: [
      "À 2 minutes en voiture de Bâle (Suisse) et de l'autoroute A35",
      "Port rhénan actif, canal du Rhône au Rhin",
      "Quartier République avec immeubles XVIIIe et XIXe siècles",
      "Proximité directe de l'EuroAirport Bâle-Mulhouse",
      "Zone franche et tissu économique transfrontalier fort",
    ],
    communesAlentours: ["Huningue", "Village-Neuf", "Hésingue", "Hégenheim", "Blotzheim"],
    seoTitle: "Rénovation Saint-Louis (68300) | Artisan AIMAN",
    seoDescription:
      "Artisan rénovation à Saint-Louis 68300 — cuisine, salle de bain, carrelage, peinture. 19 ans d'expérience. Devis gratuit sous 48h, intervention rapide.",
  },
  {
    slug: "huningue",
    name: "Huningue",
    codePostal: "68330",
    population: 7000,
    distance: 2,
    featuredImage: "/images/villes/huningue.webp",
    specificites: [
      "Frontière suisse directe, pont du Rhin vers Bâle",
      "Parc des Eaux Vives en bord de Rhin",
      "Architecture XIXe marquée par l'histoire militaire (citadelle de Vauban)",
      "Quartier gare réhabilité, forte pression immobilière transfrontalière",
    ],
    communesAlentours: ["Saint-Louis", "Village-Neuf", "Rosenau", "Kembs", "Hégenheim"],
    seoTitle: "Rénovation Huningue (68330) | Artisan AIMAN",
    seoDescription:
      "Rénovation intérieure et extérieure à Huningue 68330. Artisan qualifié proche frontière suisse. Cuisine, salle de bain, peinture. Devis gratuit.",
  },
  {
    slug: "village-neuf",
    name: "Village-Neuf",
    codePostal: "68128",
    population: 3000,
    distance: 3,
    featuredImage: "/images/villes/village-neuf.webp",
    specificites: [
      "Commune riveraine du Grand Canal d'Alsace",
      "Zones résidentielles récentes avec lotissements pavillonnaires",
      "Cadre naturel en bord de Rhin, espace vert classé",
    ],
    communesAlentours: ["Huningue", "Saint-Louis", "Rosenau", "Ottmarsheim", "Kembs"],
    seoTitle: "Rénovation Village-Neuf (68128) | Artisan AIMAN",
    seoDescription:
      "Artisan rénovation à Village-Neuf 68128, bord du Rhin. Cuisine, carrelage, peinture, salle de bain. Intervention rapide depuis Saint-Louis. Devis gratuit.",
  },
  {
    slug: "hesingue",
    name: "Hésingue",
    codePostal: "68220",
    population: 2000,
    distance: 4,
    featuredImage: "/images/villes/hesingue.webp",
    specificites: [
      "Commune résidentielle aisée en périphérie de Saint-Louis",
      "Proximité immédiate de l'EuroAirport Bâle-Mulhouse (2 km)",
      "Lotissements récents, maisons individuelles à hauts standards",
    ],
    communesAlentours: ["Saint-Louis", "Blotzheim", "Hégenheim", "Bartenheim", "Buschwiller"],
    seoTitle: "Rénovation Hésingue (68220) | Artisan AIMAN",
    seoDescription:
      "Rénovation maison à Hésingue 68220, proche EuroAirport Bâle-Mulhouse. Peinture, carrelage, isolation, salle de bain. Artisan local. Devis gratuit sous 48h.",
  },
  {
    slug: "hegenheim",
    name: "Hégenheim",
    codePostal: "68220",
    population: 3000,
    distance: 4,
    featuredImage: "/images/villes/hegenheim.webp",
    specificites: [
      "Village à la frontière directe avec la Suisse (Canton de Bâle-Ville)",
      "Maisons alsaciennes à colombages caractéristiques",
      "Tissu pavillonnaire mixte, ancienne ferme viticole reconvertie",
    ],
    communesAlentours: ["Saint-Louis", "Hésingue", "Buschwiller", "Blotzheim", "Folgensbourg"],
    seoTitle: "Rénovation Hégenheim (68220) | Artisan AIMAN",
    seoDescription:
      "Artisan rénovation à Hégenheim 68220. Maisons alsaciennes, rénovation cuisine et salle de bain. Devis gratuit, intervention rapide depuis Saint-Louis.",
  },
  {
    slug: "bartenheim",
    name: "Bartenheim",
    codePostal: "68870",
    population: 3000,
    distance: 6,
    featuredImage: "/images/villes/bartenheim.webp",
    specificites: [
      "Commune du Sundgau avec gare TER ligne Mulhouse–Bâle",
      "Zones pavillonnaires en expansion, population croissante",
      "Centre bourg alsacien avec mairie et commerces de proximité",
    ],
    communesAlentours: ["Sierentz", "Hésingue", "Blotzheim", "Saint-Louis", "Michelbach-le-Bas"],
    seoTitle: "Rénovation Bartenheim (68870) | Artisan AIMAN",
    seoDescription:
      "Rénovation intérieure et extérieure à Bartenheim 68870 (Sundgau). Cuisine, peinture, carrelage, isolation. Artisan qualifié. Devis gratuit sous 48h.",
  },
  {
    slug: "blotzheim",
    name: "Blotzheim",
    codePostal: "68730",
    population: 4000,
    distance: 5,
    featuredImage: "/images/villes/blotzheim.webp",
    specificites: [
      "Commune attenante à l'EuroAirport Bâle-Mulhouse",
      "Tissu résidentiel dense, forte demande en rénovation locative",
      "Développement économique lié à la zone aéroportuaire",
    ],
    communesAlentours: ["Saint-Louis", "Hésingue", "Bartenheim", "Michelbach-le-Bas", "Hégenheim"],
    seoTitle: "Rénovation Blotzheim (68730) | Artisan AIMAN",
    seoDescription:
      "Artisan rénovation à Blotzheim 68730, proche EuroAirport. Cuisine, salle de bain, peinture, carrelage, isolation. Devis gratuit, réponse sous 48h.",
  },
  {
    slug: "kembs",
    name: "Kembs",
    codePostal: "68680",
    population: 5000,
    distance: 8,
    featuredImage: "/images/villes/kembs.webp",
    specificites: [
      "Écluse historique du Rhin, patrimoine industriel hydraulique classé",
      "Bord du Grand Canal d'Alsace, pisciculture traditionnelle",
      "Maisons de pêcheurs et bâti ancien à restaurer",
      "Destination touristique rhénane avec hébergements à rénover",
    ],
    communesAlentours: ["Sierentz", "Village-Neuf", "Huningue", "Ottmarsheim", "Bartenheim"],
    seoTitle: "Rénovation Kembs (68680) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation bâti ancien et maisons à Kembs 68680, bord du Rhin. Façade, peinture, carrelage, cuisine, salle de bain. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "sierentz",
    name: "Sierentz",
    codePostal: "68510",
    population: 3000,
    distance: 10,
    featuredImage: "/images/villes/sierentz.webp",
    specificites: [
      "Chef-lieu de canton du Haut-Rhin, centre bourg actif",
      "Église Saint-Laurent du XIXe siècle, architecture religieuse alsacienne",
      "Communes rurales environnantes en plein développement résidentiel",
    ],
    communesAlentours: ["Bartenheim", "Kembs", "Habsheim", "Blotzheim", "Ottmarsheim"],
    seoTitle: "Rénovation Sierentz (68510) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Sierentz 68510, chef-lieu de canton Haut-Rhin. Cuisine, salle de bain, peinture, isolation, carrelage. Devis gratuit sous 48h.",
  },
  {
    slug: "rixheim",
    name: "Rixheim",
    codePostal: "68170",
    population: 14000,
    distance: 18,
    featuredImage: "/images/villes/rixheim.webp",
    specificites: [
      "Musée du Papier Peint, unique en Europe, bâtiment historique classé",
      "Commanderie teutonique du XIIIe siècle, patrimoine médiéval",
      "Banlieue résidentielle de Mulhouse, immeubles des années 1960–1980",
    ],
    communesAlentours: ["Mulhouse", "Habsheim", "Riedisheim", "Sierentz", "Ottmarsheim"],
    seoTitle: "Rénovation Rixheim (68170) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation appartement et maison à Rixheim 68170, proche Mulhouse. Carrelage, cuisine, salle de bain, peinture. Artisan local. Devis gratuit sous 48h.",
  },
  {
    slug: "habsheim",
    name: "Habsheim",
    codePostal: "68440",
    population: 5000,
    distance: 15,
    featuredImage: "/images/villes/habsheim.webp",
    specificites: [
      "Commune résidentielle sud de l'agglomération mulhousienne",
      "Aérodrome d'Habsheim, base de vol à moteur et ULM",
      "Pavillons individuels des années 1970–1990 en besoin de rénovation",
    ],
    communesAlentours: ["Sierentz", "Rixheim", "Mulhouse", "Riedisheim", "Kembs"],
    seoTitle: "Rénovation Habsheim (68440) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Habsheim 68440. Travaux cuisine, salle de bain, sols, carrelage, peinture. Intervention rapide depuis Saint-Louis. Devis gratuit.",
  },
  {
    slug: "riedisheim",
    name: "Riedisheim",
    codePostal: "68400",
    population: 12000,
    distance: 18,
    featuredImage: "/images/villes/riedisheim.webp",
    specificites: [
      "Banlieue résidentielle directe de Mulhouse, tissu dense",
      "Parc Alfred Wallach, espace vert majeur du secteur",
      "Mix immeubles collectifs et maisons de ville à rénover",
    ],
    communesAlentours: ["Mulhouse", "Rixheim", "Habsheim", "Ottmarsheim", "Sierentz"],
    seoTitle: "Rénovation Riedisheim (68400) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation intérieure et extérieure à Riedisheim 68400. Artisan qualifié : cuisine, salle de bain, carrelage, peinture. Devis gratuit sous 48h.",
  },
  {
    slug: "mulhouse",
    name: "Mulhouse",
    codePostal: "68100",
    population: 110000,
    distance: 20,
    featuredImage: "/images/villes/mulhouse.webp",
    specificites: [
      "Cité de l'Automobile — Musée national de l'automobile, plus grande collection au monde",
      "Immeubles Art Nouveau remarquables, quartier Drouot",
      "Nouveau Bassin et quartier Dornach, projets de rénovation urbaine",
      "Tissu industriel reconverti, lofts et ateliers à rénover",
      "Deuxième ville d'Alsace, forte demande en rénovation locative",
    ],
    communesAlentours: ["Riedisheim", "Rixheim", "Habsheim", "Illzach", "Wittenheim"],
    seoTitle: "Rénovation Mulhouse (68100) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Mulhouse 68100. Appartements, maisons, commerces. Cuisine, salle de bain, peinture, carrelage, isolation. Devis gratuit sous 48h.",
  },
  {
    slug: "ottmarsheim",
    name: "Ottmarsheim",
    codePostal: "68490",
    population: 2000,
    distance: 12,
    featuredImage: "/images/villes/ottmarsheim.webp",
    specificites: [
      "Abbaye octogonale du XIe siècle classée Monument Historique",
      "Centrale hydroélectrique du Rhin, patrimoine industriel du XXe",
      "Village rhénan avec bâti ancien à restaurer",
    ],
    communesAlentours: ["Kembs", "Village-Neuf", "Rixheim", "Sierentz", "Habsheim"],
    seoTitle: "Rénovation Ottmarsheim (68490) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison et bâti ancien à Ottmarsheim 68490, bord du Rhin. Peinture, carrelage, façade, isolation. Artisan qualifié. Devis gratuit sous 48h.",
  },
  {
    slug: "rosenau",
    name: "Rosenau",
    codePostal: "68128",
    population: 2000,
    distance: 5,
    featuredImage: "/images/villes/rosenau.webp",
    specificites: [
      "Commune rurale en bord du Rhin, zones naturelles protégées",
      "Habitat individuel et maisons de campagne alsaciennes",
      "Environnement calme, proximité directe de Saint-Louis",
    ],
    communesAlentours: ["Village-Neuf", "Huningue", "Saint-Louis", "Kembs", "Ottmarsheim"],
    seoTitle: "Rénovation Rosenau (68128) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Rosenau 68128, bord du Rhin. Cuisine, carrelage, peinture, isolation. Travaux intérieurs et extérieurs. Devis gratuit depuis Saint-Louis.",
  },
  {
    slug: "buschwiller",
    name: "Buschwiller",
    codePostal: "68220",
    population: 800,
    distance: 4,
    featuredImage: "/images/villes/buschwiller.webp",
    specificites: [
      "Petit village perché sur une colline avec vue sur Bâle et le Rhin",
      "Maisons typiques alsaciennes, cadre résidentiel calme",
    ],
    communesAlentours: ["Saint-Louis", "Hégenheim", "Hésingue", "Folgensbourg", "Hagenthal-le-Bas"],
    seoTitle: "Rénovation Buschwiller (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison à Buschwiller 68220, vue sur Bâle. Peinture, carrelage, salle de bain, cuisine. Artisan local Haut-Rhin. Devis gratuit sous 48h.",
  },
  {
    slug: "folgensbourg",
    name: "Folgensbourg",
    codePostal: "68220",
    population: 1000,
    distance: 7,
    featuredImage: "/images/villes/folgensbourg.webp",
    specificites: [
      "Village du Sundgau avec vignoble alsacien",
      "Caractère rural préservé, fermes et corps de ferme à rénover",
    ],
    communesAlentours: ["Hégenheim", "Buschwiller", "Hagenthal-le-Bas", "Wentzwiller", "Saint-Louis"],
    seoTitle: "Rénovation Folgensbourg (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Folgensbourg 68220 (Sundgau). Fermes alsaciennes, maisons. Peinture, carrelage, cuisine, salle de bain. Devis gratuit sous 48h.",
  },
  {
    slug: "hagenthal-le-bas",
    name: "Hagenthal-le-Bas",
    codePostal: "68220",
    population: 1000,
    distance: 6,
    featuredImage: "/images/villes/hagenthal-le-bas.webp",
    specificites: [
      "Commune en vallée de la Birsig, à la frontière suisse",
      "Paysage bocager typique du Sundgau, maisons à colombages",
    ],
    communesAlentours: ["Buschwiller", "Folgensbourg", "Hégenheim", "Leymen", "Wentzwiller"],
    seoTitle: "Rénovation Hagenthal-le-Bas (68220) | Artisan AIMAN",
    seoDescription:
      "Rénovation maison à Hagenthal-le-Bas 68220, vallée de la Birsig. Peinture, sols, salle de bain, cuisine. Artisan local Haut-Rhin. Devis gratuit sous 48h.",
  },
  {
    slug: "leymen",
    name: "Leymen",
    codePostal: "68220",
    population: 1000,
    distance: 10,
    featuredImage: "/images/villes/leymen.webp",
    specificites: [
      "Château du Landskron, patrimoine médiéval du XIIe siècle",
      "Village frontière Sundgau-Suisse, cadre naturel boisé",
    ],
    communesAlentours: ["Hagenthal-le-Bas", "Wentzwiller", "Folgensbourg", "Hégenheim", "Buschwiller"],
    seoTitle: "Rénovation Leymen (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Leymen 68220 (Sundgau), village historique du Haut-Rhin. Cuisine, peinture, carrelage, salle de bain. Devis gratuit sous 48h.",
  },
  {
    slug: "wentzwiller",
    name: "Wentzwiller",
    codePostal: "68220",
    population: 800,
    distance: 9,
    featuredImage: "/images/villes/wentzwiller.webp",
    specificites: [
      "Sundgau rural, maisons à colombages typiques",
      "Commune préservée, habitat individuel à rénover",
    ],
    communesAlentours: ["Leymen", "Hagenthal-le-Bas", "Folgensbourg", "Michelbach-le-Bas", "Bartenheim"],
    seoTitle: "Rénovation Wentzwiller (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison à Wentzwiller 68220. Maisons alsaciennes typiques du Sundgau. Peinture, carrelage, cuisine, salle de bain. Artisan local. Devis gratuit.",
  },
  {
    slug: "michelbach-le-bas",
    name: "Michelbach-le-Bas",
    codePostal: "68730",
    population: 1000,
    distance: 8,
    featuredImage: "/images/villes/michelbach-le-bas.webp",
    specificites: [
      "Petit village résidentiel entre Saint-Louis et Bartenheim",
      "Habitat pavillonnaire récent, lotissements des années 1990–2010",
    ],
    communesAlentours: ["Bartenheim", "Blotzheim", "Hésingue", "Wentzwiller", "Sierentz"],
    seoTitle: "Rénovation Michelbach-le-Bas (68730) | Artisan AIMAN",
    seoDescription:
      "Artisan rénovation à Michelbach-le-Bas 68730. Peinture, carrelage, salle de bain, cuisine, isolation. Intervention rapide Haut-Rhin. Devis gratuit.",
  },
  {
    slug: "ferrette",
    name: "Ferrette",
    codePostal: "68480",
    population: 800,
    distance: 20,
    featuredImage: "/images/villes/ferrette.webp",
    specificites: [
      "Capitale historique du Sundgau, ville médiévale authentique",
      "Château de Ferrette, ruines du XIIe siècle avec vue panoramique",
      "Maisons à colombages typiques, vieille ville classée",
      "Tourisme patrimonial fort, hôtels et gîtes à rénover",
    ],
    communesAlentours: ["Leymen", "Folgensbourg", "Wentzwiller", "Hagenthal-le-Bas", "Rosenau"],
    seoTitle: "Rénovation Ferrette (68480) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison et bâti ancien à Ferrette 68480, capitale du Sundgau. Peinture, carrelage, façade, cuisine. Artisan qualifié Haut-Rhin. Devis gratuit.",
  },
  {
    slug: "colmar",
    name: "Colmar",
    codePostal: "68000",
    population: 70000,
    distance: 65,
    featuredImage: "/images/villes/colmar.webp",
    specificites: [
      "Capitale du vignoble alsacien, centre historique classé avec maisons à colombages",
      "Petite Venise et quartier des Tanneurs — patrimoine architectural exceptionnel",
      "Musée Unterlinden (retable d'Issenheim), rayonnement culturel international",
      "Troisième ville d'Alsace — forte demande en rénovation locative et touristique",
      "Marché de Noël réputé, nombreux gîtes et hôtels à rénover",
    ],
    communesAlentours: ["Ingersheim", "Wintzenheim", "Horbourg-Wihr", "Turckheim", "Ribeauvillé"],
    seoTitle: "Rénovation Colmar (68000) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Colmar 68000 — cuisine, salle de bain, peinture, carrelage, isolation. Artisan qualifié Haut-Rhin. Devis gratuit sous 48h.",
  },
  {
    slug: "guebwiller",
    name: "Guebwiller",
    codePostal: "68500",
    population: 12000,
    distance: 50,
    featuredImage: "/images/villes/guebwiller.webp",
    specificites: [
      "Porte du Florival, au pied du Grand Ballon (point culminant des Vosges)",
      "Trois églises historiques remarquables (Saint-Léger, Notre-Dame, les Dominicains)",
      "Patrimoine industriel textile reconverti en logements et espaces culturels",
      "Vignoble grand cru Kitterlé, Kessler, Saering, Spiegel",
    ],
    communesAlentours: ["Soultz-Haut-Rhin", "Issenheim", "Buhl", "Lautenbach", "Bollwiller"],
    seoTitle: "Rénovation Guebwiller (68500) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation intérieure et extérieure à Guebwiller 68500. Artisan qualifié Haut-Rhin. Cuisine, salle de bain, peinture, isolation. Devis gratuit.",
  },
  {
    slug: "wittenheim",
    name: "Wittenheim",
    codePostal: "68270",
    population: 16000,
    distance: 22,
    featuredImage: "/images/villes/wittenheim.webp",
    specificites: [
      "Ancienne cité minière (potasse), patrimoine minier reconverti",
      "Cités ouvrières des mines de potasse à rénover et valoriser",
      "Parc du château de Wittenheim, cadre résidentiel verdoyant",
      "Proximité directe de Mulhouse, forte demande en rénovation",
    ],
    communesAlentours: ["Kingersheim", "Pfastatt", "Mulhouse", "Illzach", "Wittelsheim"],
    seoTitle: "Rénovation Wittenheim (68270) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Wittenheim 68270. Cités minières, maisons individuelles, appartements. Cuisine, peinture, carrelage. Devis gratuit sous 48h.",
  },
  {
    slug: "illzach",
    name: "Illzach",
    codePostal: "68110",
    population: 15000,
    distance: 20,
    featuredImage: "/images/villes/illzach.webp",
    specificites: [
      "Banlieue nord de Mulhouse avec zone commerciale importante (Île Napoléon)",
      "Quartiers résidentiels des années 1960-1980, pavillons à rénover",
      "Confluent de l'Ill et du canal du Rhône au Rhin",
      "Zone économique active, rénovation de locaux commerciaux",
    ],
    communesAlentours: ["Mulhouse", "Kingersheim", "Wittenheim", "Sausheim", "Rixheim"],
    seoTitle: "Rénovation Illzach (68110) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Illzach 68110, agglomération mulhousienne. Cuisine, salle de bain, sols, peinture, isolation. Artisan qualifié. Devis gratuit sous 48h.",
  },
  {
    slug: "kingersheim",
    name: "Kingersheim",
    codePostal: "68260",
    population: 13000,
    distance: 22,
    featuredImage: "/images/villes/kingersheim.webp",
    specificites: [
      "Commune du bassin potassique, ancienne cité minière reconvertie",
      "Espace Tival — pôle culturel et associatif dynamique",
      "Maisons individuelles et logements collectifs des années 1970-1990",
      "Forte demande de rénovation énergétique (isolation, chauffage)",
    ],
    communesAlentours: ["Wittenheim", "Pfastatt", "Mulhouse", "Illzach", "Lutterbach"],
    seoTitle: "Rénovation Kingersheim (68260) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Kingersheim 68260. Maisons, appartements, isolation thermique. Cuisine, salle de bain, carrelage, peinture. Devis gratuit sous 48h.",
  },
  {
    slug: "wittelsheim",
    name: "Wittelsheim",
    codePostal: "68310",
    population: 10000,
    distance: 28,
    featuredImage: "/images/villes/wittelsheim.webp",
    specificites: [
      "Ancienne commune minière (mines de potasse d'Alsace)",
      "Cités Amélie et Joseph — architecture ouvrière patrimoniale",
      "Reconversion résidentielle et culturelle du bassin potassique",
      "Habitat individuel dense, forte demande de modernisation",
    ],
    communesAlentours: ["Cernay", "Wittenheim", "Staffelfelden", "Bollwiller", "Ensisheim"],
    seoTitle: "Rénovation Wittelsheim (68310) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Wittelsheim 68310, bassin potassique. Cités minières et maisons. Peinture, carrelage, isolation, cuisine. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "cernay",
    name: "Cernay",
    codePostal: "68700",
    population: 12000,
    distance: 35,
    featuredImage: "/images/villes/cernay.webp",
    specificites: [
      "Porte sud du vignoble alsacien et du massif vosgien",
      "Zone industrielle active (mécanique, textile reconverti)",
      "Centre-ville reconstruit après les destructions de la Grande Guerre",
      "Tissu résidentiel mixte, pavillons et immeubles à rénover",
    ],
    communesAlentours: ["Thann", "Wittelsheim", "Steinbach", "Wattwiller", "Vieux-Thann"],
    seoTitle: "Rénovation Cernay (68700) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Cernay 68700. Cuisine, salle de bain, peinture, carrelage, isolation. Intervention Haut-Rhin sud. Devis gratuit sous 48h.",
  },
  {
    slug: "thann",
    name: "Thann",
    codePostal: "68800",
    population: 8000,
    distance: 40,
    featuredImage: "/images/villes/thann.webp",
    specificites: [
      "Collégiale Saint-Thiébaut — joyau gothique du Haut-Rhin, classé Monument Historique",
      "Ruine de l'Engelbourg (Oeil de la Sorcière), patrimoine médiéval",
      "Vignoble grand cru Rangen, le plus méridional d'Alsace",
      "Vallée de la Thur, accès direct au massif vosgien",
    ],
    communesAlentours: ["Cernay", "Vieux-Thann", "Bitschwiller-lès-Thann", "Leimbach", "Aspach-le-Bas"],
    seoTitle: "Rénovation Thann (68800) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation intérieure et extérieure à Thann 68800. Artisan qualifié Haut-Rhin. Peinture, carrelage, façade, cuisine, salle de bain. Devis gratuit sous 48h.",
  },
  {
    slug: "altkirch",
    name: "Altkirch",
    codePostal: "68130",
    population: 6000,
    distance: 25,
    featuredImage: "/images/villes/altkirch.webp",
    specificites: [
      "Capitale du Sundgau, chef-lieu d'arrondissement",
      "Centre historique médiéval perché sur une colline",
      "Maisons à colombages et patrimoine sundgauvien remarquable",
      "Pôle économique et administratif du sud Haut-Rhin",
    ],
    communesAlentours: ["Carspach", "Hirsingue", "Aspach", "Waldighofen", "Ferrette"],
    seoTitle: "Rénovation Altkirch (68130) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Altkirch 68130, capitale du Sundgau. Maisons alsaciennes et bâti ancien. Cuisine, salle de bain, peinture, carrelage. Devis gratuit.",
  },
  {
    slug: "soultz-haut-rhin",
    name: "Soultz-Haut-Rhin",
    codePostal: "68360",
    population: 7000,
    distance: 45,
    featuredImage: "/images/villes/soultz-haut-rhin.webp",
    specificites: [
      "Cité historique au pied du vignoble, maisons Renaissance et colombages",
      "Château du Bucheneck (musée), patrimoine médiéval",
      "Nef des Jouets — musée unique, tourisme familial",
      "Vignoble grand cru Ollwiller, Zinnkoepflé à proximité",
    ],
    communesAlentours: ["Guebwiller", "Issenheim", "Wuenheim", "Jungholtz", "Bollwiller"],
    seoTitle: "Rénovation Soultz-Haut-Rhin (68360) | Artisan AIMAN",
    seoDescription:
      "Rénovation à Soultz-Haut-Rhin 68360. Maisons anciennes du vignoble alsacien. Cuisine, salle de bain, peinture, carrelage. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "brunstatt-didenheim",
    name: "Brunstatt-Didenheim",
    codePostal: "68350",
    population: 8000,
    distance: 20,
    featuredImage: "/images/villes/brunstatt-didenheim.webp",
    specificites: [
      "Commune fusionnée en 2016, banlieue résidentielle sud de Mulhouse",
      "Tissu pavillonnaire des années 1970-1990, forte demande de rénovation",
      "Cadre verdoyant et calme, attractif pour les familles",
      "Proximité directe du centre de Mulhouse et de la gare TGV",
    ],
    communesAlentours: ["Mulhouse", "Riedisheim", "Flaxlanden", "Zillisheim", "Pfastatt"],
    seoTitle: "Rénovation Brunstatt-Didenheim (68350) | Artisan AIMAN",
    seoDescription:
      "Artisan rénovation à Brunstatt-Didenheim 68350. Pavillons, maisons individuelles. Cuisine, salle de bain, carrelage, isolation. Devis gratuit sous 48h.",
  },
  {
    slug: "pfastatt",
    name: "Pfastatt",
    codePostal: "68120",
    population: 9000,
    distance: 22,
    featuredImage: "/images/villes/pfastatt.webp",
    specificites: [
      "Banlieue ouest de Mulhouse, commune résidentielle familiale",
      "Maisons individuelles et petits collectifs des années 1960-1980",
      "Tissu associatif dense, vie locale dynamique",
      "Besoin important en rénovation énergétique et modernisation",
    ],
    communesAlentours: ["Mulhouse", "Kingersheim", "Lutterbach", "Wittenheim", "Brunstatt-Didenheim"],
    seoTitle: "Rénovation Pfastatt (68120) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Pfastatt 68120, agglomération mulhousienne. Cuisine, salle de bain, peinture, carrelage, isolation. Artisan qualifié. Devis gratuit sous 48h.",
  },
  {
    slug: "lutterbach",
    name: "Lutterbach",
    codePostal: "68460",
    population: 6000,
    distance: 24,
    featuredImage: "/images/villes/lutterbach.webp",
    specificites: [
      "Commune résidentielle à l'ouest de Mulhouse, vallée de la Doller",
      "Gare TER sur la ligne Mulhouse–Thann, bonne desserte ferroviaire",
      "Pavillons des années 1970-1990, immeubles récents en développement",
      "Proximité commerciale (ZAC du Kaligone)",
    ],
    communesAlentours: ["Pfastatt", "Kingersheim", "Mulhouse", "Wittelsheim", "Reiningue"],
    seoTitle: "Rénovation Lutterbach (68460) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Lutterbach 68460, vallée de la Doller. Maisons, appartements. Cuisine, peinture, carrelage, isolation. Devis gratuit sous 48h.",
  },
  {
    slug: "ensisheim",
    name: "Ensisheim",
    codePostal: "68190",
    population: 7000,
    distance: 28,
    featuredImage: "/images/villes/ensisheim.webp",
    specificites: [
      "Ancienne capitale de la Haute-Alsace des Habsbourg, patrimoine historique riche",
      "Palais de la Régence (XVIe siècle), musée de la météorite d'Ensisheim",
      "Centre pénitentiaire et zone économique, tissu urbain varié",
      "Bassin potassique, proximité des cités minières à rénover",
    ],
    communesAlentours: ["Bollwiller", "Wittelsheim", "Réguisheim", "Meyenheim", "Ungersheim"],
    seoTitle: "Rénovation Ensisheim (68190) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Ensisheim 68190, ancienne capitale des Habsbourg. Bâti ancien, maisons modernes. Cuisine, peinture, carrelage, salle de bain. Devis gratuit.",
  },
  {
    slug: "rouffach",
    name: "Rouffach",
    codePostal: "68250",
    population: 5000,
    distance: 55,
    featuredImage: "/images/villes/rouffach.webp",
    specificites: [
      "Cité viticole historique au cœur du vignoble alsacien",
      "Église Notre-Dame de l'Assomption, patrimoine roman et gothique",
      "Lycée agricole et viticole, centre de formation reconnu",
      "Vignoble grand cru Vorbourg, maisons vigneronnes à rénover",
    ],
    communesAlentours: ["Soultzmatt", "Pfaffenheim", "Westhalten", "Gueberschwihr", "Issenheim"],
    seoTitle: "Rénovation Rouffach (68250) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Rouffach 68250, cité viticole du Haut-Rhin. Maisons vigneronnes, cuisine, salle de bain, peinture, carrelage. Devis gratuit sous 48h.",
  },
  {
    slug: "munster",
    name: "Munster",
    codePostal: "68140",
    population: 5000,
    distance: 70,
    featuredImage: "/images/villes/munster.webp",
    specificites: [
      "Capitale de la vallée de Munster, berceau du célèbre fromage éponyme",
      "Abbaye bénédictine fondatrice (VIIe siècle), patrimoine historique",
      "Centre-ville reconstruit après 1945, architecture mixte",
      "Tourisme vosgien actif, hôtels et gîtes à rénover",
    ],
    communesAlentours: ["Gunsbach", "Griesbach-au-Val", "Luttenbach-près-Munster", "Hohrod", "Stosswihr"],
    seoTitle: "Rénovation Munster (68140) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Munster 68140, vallée vosgienne du Haut-Rhin. Maisons, gîtes, hôtels. Cuisine, salle de bain, isolation, carrelage. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "sainte-marie-aux-mines",
    name: "Sainte-Marie-aux-Mines",
    codePostal: "68160",
    population: 5000,
    distance: 80,
    featuredImage: "/images/villes/sainte-marie-aux-mines.webp",
    specificites: [
      "Val d'Argent — patrimoine minier exceptionnel (argent, plomb, cobalt)",
      "Salon Mineral & Gem de renommée mondiale",
      "Patrimoine textile (ancienne industrie du tissage)",
      "Tunnel Maurice Lemaire reliant l'Alsace à la Lorraine",
    ],
    communesAlentours: ["Lièpvre", "Rombach-le-Franc", "Echéry", "Fertrupt", "Ribeauvillé"],
    seoTitle: "Rénovation Sainte-Marie-aux-Mines (68160) | Artisan AIMAN",
    seoDescription:
      "Artisan rénovation à Sainte-Marie-aux-Mines 68160, Val d'Argent. Maisons anciennes, peinture, carrelage, isolation, salle de bain. Devis gratuit.",
  },
  {
    slug: "bollwiller",
    name: "Bollwiller",
    codePostal: "68540",
    population: 4000,
    distance: 30,
    featuredImage: "/images/villes/bollwiller.webp",
    specificites: [
      "Noeud ferroviaire historique (gare de jonction Mulhouse–Guebwiller)",
      "Commune résidentielle entre plaine et piémont vosgien",
      "Bassin potassique, cités ouvrières reconverties",
      "Demande croissante en rénovation énergétique",
    ],
    communesAlentours: ["Soultz-Haut-Rhin", "Ensisheim", "Wittelsheim", "Staffelfelden", "Guebwiller"],
    seoTitle: "Rénovation Bollwiller (68540) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Bollwiller 68540. Maisons, appartements. Cuisine, salle de bain, peinture, carrelage, isolation. Artisan qualifié Haut-Rhin. Devis gratuit sous 48h.",
  },
  {
    slug: "orbey",
    name: "Orbey",
    codePostal: "68370",
    population: 3500,
    distance: 75,
    featuredImage: "/images/villes/orbey.webp",
    specificites: [
      "Commune de montagne au cœur du massif vosgien (vallée de l'Orbey)",
      "Station touristique été/hiver, sports de pleine nature",
      "Lac Noir et Lac Blanc, sites naturels remarquables",
      "Chalets et maisons vosgiennes à rénover pour location saisonnière",
    ],
    communesAlentours: ["Kaysersberg-Vignoble", "Labaroche", "Lapoutroie", "Le Bonhomme", "Pairis"],
    seoTitle: "Rénovation Orbey (68370) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Orbey 68370, montagne vosgienne du Haut-Rhin. Chalets, maisons, gîtes. Isolation, peinture, salle de bain, aménagement. Devis gratuit.",
  },
  {
    slug: "kaysersberg-vignoble",
    name: "Kaysersberg-Vignoble",
    codePostal: "68240",
    population: 4500,
    distance: 68,
    featuredImage: "/images/villes/kaysersberg-vignoble.webp",
    specificites: [
      "Village préféré des Français 2017, destination touristique majeure",
      "Château impérial médiéval, maisons à colombages Renaissance",
      "Vignoble grand cru Schlossberg, Kaefferkopf",
      "Tourisme haut de gamme, gîtes et hôtels de charme à rénover",
    ],
    communesAlentours: ["Orbey", "Ammerschwihr", "Kientzheim", "Sigolsheim", "Turckheim"],
    seoTitle: "Rénovation Kaysersberg-Vignoble (68240) | Artisan AIMAN",
    seoDescription:
      "Rénovation à Kaysersberg-Vignoble 68240. Maisons à colombages, gîtes, hôtels du vignoble. Peinture, carrelage, façade. Artisan qualifié. Devis gratuit sous 48h.",
  },
  {
    slug: "ribeauville",
    name: "Ribeauvillé",
    codePostal: "68150",
    population: 5000,
    distance: 72,
    featuredImage: "/images/villes/ribeauville.webp",
    specificites: [
      "Cité des Ménétriers, trois châteaux médiévaux surplombant la ville",
      "Grand Rue avec maisons à colombages et oriels remarquables",
      "Vignoble grand cru Geisberg, Kirchberg de Ribeauvillé, Osterberg",
      "Fête des Ménétriers (Pfifferdaj), tradition folklorique vivante",
    ],
    communesAlentours: ["Bergheim", "Hunawihr", "Saint-Hippolyte", "Guémar", "Sainte-Marie-aux-Mines"],
    seoTitle: "Rénovation Ribeauvillé (68150) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Ribeauvillé 68150, cité des Ménétriers. Colombages, bâti ancien, peinture, carrelage, façade. Artisan qualifié Haut-Rhin. Devis gratuit.",
  },
  {
    slug: "turckheim",
    name: "Turckheim",
    codePostal: "68230",
    population: 3800,
    distance: 63,
    featuredImage: "/images/villes/turckheim.webp",
    specificites: [
      "Cité fortifiée avec trois portes médiévales et remparts conservés",
      "Veilleur de nuit, tradition unique en France maintenue chaque soir",
      "Vignoble grand cru Brand, terroir viticole d'exception",
      "Tourisme patrimonial et viticole, hébergements à rénover",
    ],
    communesAlentours: ["Colmar", "Wintzenheim", "Kaysersberg-Vignoble", "Niedermorschwihr", "Ingersheim"],
    seoTitle: "Rénovation Turckheim (68230) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Turckheim 68230, cité fortifiée médiévale. Maisons alsaciennes et colombages. Peinture, carrelage, façade, cuisine. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "sausheim",
    name: "Sausheim",
    codePostal: "68390",
    population: 5500,
    distance: 18,
    featuredImage: "/images/villes/sausheim.webp",
    specificites: [
      "Commune résidentielle nord de Mulhouse, zone d'activité économique",
      "Parc Expo Mulhouse (SEPAM), pôle événementiel du Haut-Rhin",
      "Lotissements pavillonnaires récents et maisons des années 1980",
      "Desserte autoroutière A36, attractivité résidentielle croissante",
    ],
    communesAlentours: ["Illzach", "Mulhouse", "Rixheim", "Habsheim", "Baldersheim"],
    seoTitle: "Rénovation Sausheim (68390) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Sausheim 68390, nord de Mulhouse. Pavillons, cuisine, salle de bain, peinture, carrelage, isolation. Intervention rapide. Devis gratuit.",
  },
];
