export interface VilleFR {
  slug: string;
  name: string;
  codePostal: string;
  population?: number;
  distance: number; // km depuis Saint-Louis
  featuredImage: string;
  specificites: string[]; // 3-5 points uniques (histoire, architecture, économie)
  communesAlentours: string[];
  seoTitle: string;
  seoDescription: string;
}

export const VILLES_FR: VilleFR[] = [
  {
    slug: "saint-louis",
    name: "Saint-Louis",
    codePostal: "68300",
    population: 21000,
    distance: 0,
    featuredImage: "/images/villes/saint-louis.webp",
    specificites: [
      "À 2 minutes en voiture de Bâle (Suisse) et de l'autoroute A35",
      "Port rhénan actif, canal du Rhône au Rhin",
      "Quartier République avec immeubles XVIIIe et XIXe siècles",
      "Proximité directe de l'EuroAirport Bâle-Mulhouse",
      "Zone franche et tissu économique transfrontalier fort",
    ],
    communesAlentours: ["Huningue", "Village-Neuf", "Hésingue", "Hégenheim", "Blotzheim"],
    seoTitle: "Rénovation Saint-Louis (68300) | Artisan Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Saint-Louis 68300 — cuisine, salle de bain, carrelage, peinture, façade. 19 ans d'expérience, zone tri-frontière. Devis gratuit.",
  },
  {
    slug: "huningue",
    name: "Huningue",
    codePostal: "68330",
    population: 7000,
    distance: 2,
    featuredImage: "/images/villes/huningue.webp",
    specificites: [
      "Frontière suisse directe, pont du Rhin vers Bâle",
      "Parc des Eaux Vives en bord de Rhin",
      "Architecture XIXe marquée par l'histoire militaire (citadelle de Vauban)",
      "Quartier gare réhabilité, forte pression immobilière transfrontalière",
    ],
    communesAlentours: ["Saint-Louis", "Village-Neuf", "Rosenau", "Kembs", "Hégenheim"],
    seoTitle: "Rénovation Huningue 68330 | Artisan Qualifié Haut-Rhin",
    seoDescription:
      "Rénovation intérieure et extérieure à Huningue 68330, proche frontière suisse. Cuisine, salle de bain, carrelage, peinture. Artisan local — devis gratuit.",
  },
  {
    slug: "village-neuf",
    name: "Village-Neuf",
    codePostal: "68128",
    population: 3000,
    distance: 3,
    featuredImage: "/images/villes/village-neuf.webp",
    specificites: [
      "Commune riveraine du Grand Canal d'Alsace",
      "Zones résidentielles récentes avec lotissements pavillonnaires",
      "Cadre naturel en bord de Rhin, espace vert classé",
    ],
    communesAlentours: ["Huningue", "Saint-Louis", "Rosenau", "Ottmarsheim", "Kembs"],
    seoTitle: "Rénovation Village-Neuf (68128) | Artisan Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Village-Neuf 68128, bord du Rhin. Cuisine, carrelage, peinture, salle de bain. Intervention rapide depuis Saint-Louis. Devis gratuit.",
  },
  {
    slug: "hesingue",
    name: "Hésingue",
    codePostal: "68220",
    population: 2000,
    distance: 4,
    featuredImage: "/images/villes/hesingue.webp",
    specificites: [
      "Commune résidentielle aisée en périphérie de Saint-Louis",
      "Proximité immédiate de l'EuroAirport Bâle-Mulhouse (2 km)",
      "Lotissements récents, maisons individuelles à hauts standards",
    ],
    communesAlentours: ["Saint-Louis", "Hégenheim", "Buschwiller", "Folgensbourg", "Hagenthal-le-Bas"],
    seoTitle: "Rénovation Hésingue 68220 | Artisan Qualifié Haut-Rhin",
    seoDescription:
      "Rénovation maison à Hésingue 68220, proche EuroAirport Bâle-Mulhouse. Peinture, carrelage, isolation, salle de bain. Artisan local. Devis gratuit sous 48h.",
  },
  {
    slug: "hegenheim",
    name: "Hégenheim",
    codePostal: "68220",
    population: 3000,
    distance: 4,
    featuredImage: "/images/villes/hegenheim.webp",
    specificites: [
      "Village résidentiel transfrontalier (frontière suisse à 1 km)",
      "Forte proportion de frontaliers travaillant à Bâle",
      "Maisons alsaciennes rénovées, colombages restaurés",
    ],
    communesAlentours: ["Saint-Louis", "Hésingue", "Buschwiller", "Folgensbourg", "Blotzheim"],
    seoTitle: "Rénovation Hégenheim (68220) | Artisan Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Hégenheim 68220. Maisons alsaciennes, rénovation cuisine et salle de bain. Devis gratuit, intervention rapide depuis Saint-Louis.",
  },
  {
    slug: "bartenheim",
    name: "Bartenheim",
    codePostal: "68870",
    population: 3000,
    distance: 6,
    featuredImage: "/images/villes/bartenheim.webp",
    specificites: [
      "Chef-lieu de canton du Sundgau alsacien",
      "Tissu pavillonnaire dense, nombreuses rénovations en cours",
      "Bonne accessibilité routière (D419, A35)",
    ],
    communesAlentours: ["Blotzheim", "Sierentz", "Kembs", "Rixheim", "Habsheim"],
    seoTitle: "Rénovation Bartenheim (68870) | Artisan Haut-Rhin",
    seoDescription:
      "Rénovation intérieure et extérieure à Bartenheim 68870 (Sundgau). Cuisine, peinture, carrelage, isolation. Artisan qualifié. Devis gratuit sous 48h.",
  },
  {
    slug: "blotzheim",
    name: "Blotzheim",
    codePostal: "68730",
    population: 4000,
    distance: 5,
    featuredImage: "/images/villes/blotzheim.webp",
    specificites: [
      "Commune aéroportuaire — EuroAirport Bâle-Mulhouse-Fribourg en limite de territoire",
      "Tissu résidentiel mixte (ancien et récent)",
      "Fort développement immobilier lié au bassin d'emploi transfrontalier",
    ],
    communesAlentours: ["Saint-Louis", "Hégenheim", "Hésingue", "Bartenheim", "Leymen"],
    seoTitle: "Rénovation Blotzheim (68730) | Artisan Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Blotzheim 68730, proche EuroAirport. Cuisine, salle de bain, peinture, carrelage, isolation. Devis gratuit, réponse sous 48h.",
  },
  {
    slug: "kembs",
    name: "Kembs",
    codePostal: "68680",
    population: 5000,
    distance: 8,
    featuredImage: "/images/villes/kembs.webp",
    specificites: [
      "Commune fluviale sur le Grand Canal d'Alsace",
      "Secteur pavillonnaire développé dans les années 1970-1990",
      "Zone de calme entre Mulhouse et Saint-Louis",
    ],
    communesAlentours: ["Sierentz", "Village-Neuf", "Huningue", "Ottmarsheim", "Bartenheim"],
    seoTitle: "Rénovation Kembs (68680) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation bâti ancien et maisons à Kembs 68680, bord du Rhin. Artisan qualifié. Façade, peinture, carrelage. Devis gratuit.",
  },
  {
    slug: "sierentz",
    name: "Sierentz",
    codePostal: "68510",
    population: 3500,
    distance: 9,
    featuredImage: "/images/villes/sierentz.webp",
    specificites: [
      "Chef-lieu de canton (canton de Sierentz)",
      "Commune en forte croissance démographique",
      "Tissu pavillonnaire récent, nombreux lotissements",
    ],
    communesAlentours: ["Bartenheim", "Kembs", "Rosenau", "Rixheim", "Habsheim"],
    seoTitle: "Rénovation Sierentz (68510) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Sierentz 68510, chef-lieu de canton. Cuisine, salle de bain, peinture, carrelage, façade. Devis gratuit sous 48h.",
  },
  {
    slug: "rixheim",
    name: "Rixheim",
    codePostal: "68170",
    population: 6000,
    distance: 12,
    featuredImage: "/images/villes/rixheim.webp",
    specificites: [
      "Banlieue résidentielle de Mulhouse, forte densité",
      "Musée du Papier Peint (institution nationale)",
      "Quartiers mixtes ancien/récent avec potentiel de rénovation",
    ],
    communesAlentours: ["Mulhouse", "Habsheim", "Riedisheim", "Sierentz", "Bartenheim"],
    seoTitle: "Rénovation Rixheim (68170) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation appartement et maison à Rixheim 68170, proche Mulhouse. Carrelage, cuisine, peinture, salle de bain. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "habsheim",
    name: "Habsheim",
    codePostal: "68440",
    population: 5000,
    distance: 11,
    featuredImage: "/images/villes/habsheim.webp",
    specificites: [
      "Commune résidentielle entre Mulhouse et Saint-Louis",
      "Centre aéré et zones pavillonnaires récentes",
      "Tissu commercial local dynamique",
    ],
    communesAlentours: ["Rixheim", "Riedisheim", "Sierentz", "Kembs", "Bartenheim"],
    seoTitle: "Rénovation Habsheim (68440) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Habsheim 68440, entre Mulhouse et Saint-Louis. Cuisine, salle de bain, peinture, carrelage. Devis gratuit sous 48h.",
  },
  {
    slug: "riedisheim",
    name: "Riedisheim",
    codePostal: "68400",
    population: 12000,
    distance: 14,
    featuredImage: "/images/villes/riedisheim.webp",
    specificites: [
      "Commune de l'agglomération mulhousienne (12 000 hab.)",
      "Tissu urbain dense, appartements et maisons de ville",
      "Potentiel de rénovation élevé (parc immobilier des années 1960-1980)",
    ],
    communesAlentours: ["Mulhouse", "Rixheim", "Habsheim", "Illzach", "Wittenheim"],
    seoTitle: "Rénovation Riedisheim (68400) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation intérieure à Riedisheim 68400. Artisan qualifié, cuisine, salle de bain, carrelage, peinture. Intervention rapide. Devis gratuit.",
  },
  {
    slug: "mulhouse",
    name: "Mulhouse",
    codePostal: "68100",
    population: 112000,
    distance: 15,
    featuredImage: "/images/villes/mulhouse.webp",
    specificites: [
      "2e ville d'Alsace (112 000 hab.), fort potentiel rénovation",
      "Parc immobilier dense années 1950-1980, souvent vétuste",
      "Forte activité locative et investissement immobilier",
      "Cité du train, musée de l'auto — ville culturelle",
    ],
    communesAlentours: ["Riedisheim", "Rixheim", "Habsheim", "Illzach", "Wittenheim"],
    seoTitle: "Rénovation Mulhouse (68100) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Mulhouse 68100. Appartements, maisons et commerces. Cuisine, salle de bain, peinture, carrelage, isolation. Devis gratuit.",
  },
  {
    slug: "ottmarsheim",
    name: "Ottmarsheim",
    codePostal: "68490",
    population: 2500,
    distance: 10,
    featuredImage: "/images/villes/ottmarsheim.webp",
    specificites: [
      "Commune industrielle (centrale hydroélectrique EDF sur le Rhin)",
      "Abbatiale romane du XIe siècle (monument historique)",
      "Fort développement pavillonnaire récent",
    ],
    communesAlentours: ["Kembs", "Village-Neuf", "Huningue", "Sierentz", "Bartenheim"],
    seoTitle: "Rénovation Ottmarsheim (68490) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison et bâti ancien à Ottmarsheim 68490, bord du Rhin. Artisan qualifié. Peinture, carrelage, salle de bain, isolation. Devis gratuit.",
  },
  {
    slug: "rosenau",
    name: "Rosenau",
    codePostal: "68128",
    population: 2000,
    distance: 6,
    featuredImage: "/images/villes/rosenau.webp",
    specificites: [
      "Commune rhénane en bord du Grand Canal d'Alsace",
      "Zone résidentielle calme, maisons individuelles",
      "Proche de Village-Neuf et de l'écluse de Kembs",
    ],
    communesAlentours: ["Village-Neuf", "Huningue", "Kembs", "Ottmarsheim", "Saint-Louis"],
    seoTitle: "Rénovation Rosenau (68128) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Rosenau 68128, bord du Rhin. Cuisine, salle de bain, peinture, carrelage. Intervention rapide depuis Saint-Louis. Devis gratuit.",
  },
  {
    slug: "buschwiller",
    name: "Buschwiller",
    codePostal: "68220",
    population: 1500,
    distance: 5,
    featuredImage: "/images/villes/buschwiller.webp",
    specificites: [
      "Village résidentiel avec vue sur Bâle",
      "Maisons individuelles récentes, frontaliers suisses",
      "Accès direct à Saint-Louis (5 min) et à Hégenheim",
    ],
    communesAlentours: ["Saint-Louis", "Hégenheim", "Hésingue", "Folgensbourg", "Hagenthal-le-Bas"],
    seoTitle: "Rénovation Buschwiller (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison à Buschwiller 68220, vue sur Bâle. Peinture, carrelage, salle de bain. Artisan local. Devis gratuit.",
  },
  {
    slug: "folgensbourg",
    name: "Folgensbourg",
    codePostal: "68220",
    population: 1000,
    distance: 7,
    featuredImage: "/images/villes/folgensbourg.webp",
    specificites: [
      "Village du Sundgau, paysage agricole préservé",
      "Fermes alsaciennes à rénover (grange, corps de ferme)",
      "Calme et verdure à 15 min de Bâle",
    ],
    communesAlentours: ["Hégenheim", "Buschwiller", "Hésingue", "Hagenthal-le-Bas", "Bartenheim"],
    seoTitle: "Rénovation Folgensbourg (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Folgensbourg 68220 (Sundgau). Fermes alsaciennes, intérieurs. Peinture, carrelage, isolation. Devis gratuit, intervention locale.",
  },
  {
    slug: "hagenthal-le-bas",
    name: "Hagenthal-le-Bas",
    codePostal: "68220",
    population: 1200,
    distance: 8,
    featuredImage: "/images/villes/hagenthal-le-bas.webp",
    specificites: [
      "Village de la vallée de la Birsig, frontière suisse",
      "Maisons bourgeoises et fermes alsaciennes",
      "Accès direct à Bâle via la D12 (frontière Leymen)",
    ],
    communesAlentours: ["Buschwiller", "Folgensbourg", "Hégenheim", "Leymen", "Wentzwiller"],
    seoTitle: "Rénovation Hagenthal-le-Bas (68220) | Artisan Haut-Rhin",
    seoDescription:
      "Rénovation maison à Hagenthal-le-Bas 68220, vallée de la Birsig. Peinture, carrelage, salle de bain, cuisine. Artisan local Haut-Rhin. Devis gratuit sous 48h.",
  },
  {
    slug: "leymen",
    name: "Leymen",
    codePostal: "68220",
    population: 1800,
    distance: 9,
    featuredImage: "/images/villes/leymen.webp",
    specificites: [
      "Dernière commune française avant la frontière suisse (canton Bâle-Campagne)",
      "Village résidentiel prisé, maisons bourgeoises récentes",
      "Calme, verdure, vue sur le Jura bâlois",
    ],
    communesAlentours: ["Hagenthal-le-Bas", "Folgensbourg", "Blotzheim", "Hégenheim", "Buschwiller"],
    seoTitle: "Rénovation Leymen (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison à Leymen 68220, commune frontière suisse. Cuisine, salle de bain, peinture, carrelage. Artisan local. Devis gratuit.",
  },
  {
    slug: "wentzwiller",
    name: "Wentzwiller",
    codePostal: "68220",
    population: 1500,
    distance: 7,
    featuredImage: "/images/villes/wentzwiller.webp",
    specificites: [
      "Village du Sundgau alsacien, calme résidentiel",
      "Maisons alsaciennes à colombages et fermes rénovées",
      "Bonne desserte routière vers Saint-Louis et Bartenheim",
    ],
    communesAlentours: ["Leymen", "Hagenthal-le-Bas", "Folgensbourg", "Michelbach-le-Bas", "Bartenheim"],
    seoTitle: "Rénovation Wentzwiller (68220) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison à Wentzwiller 68220. Maisons alsaciennes, peinture, carrelage, cuisine, salle de bain. Artisan local. Devis gratuit.",
  },
  {
    slug: "michelbach-le-bas",
    name: "Michelbach-le-Bas",
    codePostal: "68730",
    population: 1000,
    distance: 8,
    featuredImage: "/images/villes/michelbach-le-bas.webp",
    specificites: [
      "Village du Sundgau, proche de Bartenheim et de l'aéroport",
      "Habitat pavillonnaire récent et fermes alsaciennes",
      "Cadre verdoyant, clientèle frontalière suisse",
    ],
    communesAlentours: ["Bartenheim", "Blotzheim", "Hésingue", "Wentzwiller", "Sierentz"],
    seoTitle: "Rénovation Michelbach-le-Bas (68730) | Artisan Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Michelbach-le-Bas 68730. Peinture, carrelage, salle de bain, cuisine. Intervention rapide depuis Saint-Louis. Devis gratuit.",
  },
  {
    slug: "ferrette",
    name: "Ferrette",
    codePostal: "68480",
    population: 1000,
    distance: 20,
    featuredImage: "/images/villes/ferrette.webp",
    specificites: [
      "Ancienne capitale du Sundgau, château médiéval",
      "Bâtiment historiques à rénover avec soins",
      "Tourisme rural, gîtes et chambres d'hôtes",
    ],
    communesAlentours: ["Altkirch", "Ligsdorf", "Lucelle", "Leymen", "Walheim"],
    seoTitle: "Rénovation Ferrette (68480) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation bâtiment ancien et maison à Ferrette 68480 (Sundgau). Artisan qualifié. Façade, peinture, sols, salle de bain. Devis gratuit.",
  },
  {
    slug: "colmar",
    name: "Colmar",
    codePostal: "68000",
    population: 70000,
    distance: 65,
    featuredImage: "/images/villes/colmar.webp",
    specificites: [
      "Capitale des vins d'Alsace, centre-ville historique classé",
      "Fort potentiel de rénovation (immeubles XIXe, colombages)",
      "Tourisme massif — marché des gîtes et chambres d'hôtes",
      "Connexion TGV directe Paris-Colmar",
    ],
    communesAlentours: ["Ingersheim", "Turckheim", "Wintzenheim", "Horbourg-Wihr", "Sundhoffen"],
    seoTitle: "Rénovation Colmar (68000) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation appartement et maison à Colmar 68000. Immeubles anciens, colombages, cuisines, salles de bain. Artisan qualifié Haut-Rhin. Devis gratuit.",
  },
  {
    slug: "guebwiller",
    name: "Guebwiller",
    codePostal: "68500",
    population: 11000,
    distance: 30,
    featuredImage: "/images/villes/guebwiller.webp",
    specificites: [
      "Ville industrielle alsacienne en reconversion",
      "Vignoble grand cru Kitterlé",
      "Architectures Art Nouveau remarquables",
    ],
    communesAlentours: ["Soultz-Haut-Rhin", "Wuenheim", "Bergholtz", "Issenheim", "Merxheim"],
    seoTitle: "Rénovation Guebwiller (68500) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Guebwiller 68500. Immeubles anciens, maisons, appartements. Cuisine, salle de bain, peinture, carrelage. Devis gratuit.",
  },
  {
    slug: "wittenheim",
    name: "Wittenheim",
    codePostal: "68270",
    population: 16000,
    distance: 18,
    featuredImage: "/images/villes/wittenheim.webp",
    specificites: [
      "Commune de l'agglomération mulhousienne (16 000 hab.)",
      "Parc immobilier récent (années 1970-1990, anciens mineurs)",
      "Fort potentiel de rénovation thermique (isolation)",
    ],
    communesAlentours: ["Mulhouse", "Kingersheim", "Wittelsheim", "Illzach", "Pfastatt"],
    seoTitle: "Rénovation Wittenheim (68270) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Wittenheim 68270, agglomération mulhousienne. Cuisine, salle de bain, isolation, peinture. Devis gratuit sous 48h.",
  },
  {
    slug: "illzach",
    name: "Illzach",
    codePostal: "68110",
    population: 15000,
    distance: 16,
    featuredImage: "/images/villes/illzach.webp",
    specificites: [
      "Commune commerciale de l'agglomération mulhousienne",
      "Zone commerciale Mulhouse-Rhin importante",
      "Tissu résidentiel mixte (appartements et pavillons)",
    ],
    communesAlentours: ["Mulhouse", "Riedisheim", "Rixheim", "Habsheim", "Wittenheim"],
    seoTitle: "Rénovation Illzach (68110) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Illzach 68110, agglomération mulhousienne. Cuisine, salle de bain, sols, peinture, isolation. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "kingersheim",
    name: "Kingersheim",
    codePostal: "68260",
    population: 12000,
    distance: 17,
    featuredImage: "/images/villes/kingersheim.webp",
    specificites: [
      "Commune innovante, label Cit'ergie",
      "Tissu pavillonnaire dense",
      "Potentiel d'isolation thermique élevé",
    ],
    communesAlentours: ["Wittenheim", "Wittelsheim", "Mulhouse", "Illzach", "Pfastatt"],
    seoTitle: "Rénovation Kingersheim (68260) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Kingersheim 68260. Cuisine, salle de bain, isolation thermique, peinture. Devis gratuit, intervention rapide depuis Saint-Louis.",
  },
  {
    slug: "wittelsheim",
    name: "Wittelsheim",
    codePostal: "68310",
    population: 12000,
    distance: 20,
    featuredImage: "/images/villes/wittelsheim.webp",
    specificites: [
      "Ancienne commune minière (potasse d'Alsace)",
      "Fort tissu pavillonnaire, maisons ouvrières des années 1950-1970",
      "Potentiel de rénovation thermique très élevé",
    ],
    communesAlentours: ["Kingersheim", "Wittenheim", "Cernay", "Bollwiller", "Pfastatt"],
    seoTitle: "Rénovation Wittelsheim (68310) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Wittelsheim 68310. Maisons ouvrières, isolation, cuisine, salle de bain. Devis gratuit, intervention rapide.",
  },
  {
    slug: "cernay",
    name: "Cernay",
    codePostal: "68700",
    population: 11000,
    distance: 22,
    featuredImage: "/images/villes/cernay.webp",
    specificites: [
      "Ville industrielle à l'entrée de la vallée de la Thur",
      "Tissu mixte commercial/résidentiel",
      "Potentiel de rénovation des immeubles d'après-guerre",
    ],
    communesAlentours: ["Wittelsheim", "Thann", "Wattwiller", "Uffholtz", "Steinbach"],
    seoTitle: "Rénovation Cernay (68700) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Cernay 68700, entrée de la vallée de la Thur. Cuisine, salle de bain, peinture, isolation. Devis gratuit sous 48h.",
  },
  {
    slug: "thann",
    name: "Thann",
    codePostal: "68800",
    population: 8000,
    distance: 28,
    featuredImage: "/images/villes/thann.webp",
    specificites: [
      "Ville historique à l'entrée de la vallée de la Thur",
      "Collégiale Saint-Thiébaut (monument gothique majeur)",
      "Vignoble Rangen de Thann (grand cru)",
    ],
    communesAlentours: ["Cernay", "Vieux-Thann", "Bitschwiller-lès-Thann", "Aspach-le-Bas", "Leimbach"],
    seoTitle: "Rénovation Thann (68800) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Thann 68800, vallée de la Thur. Maisons alsaciennes, appartements, isolation, peinture, sols. Devis gratuit.",
  },
  {
    slug: "altkirch",
    name: "Altkirch",
    codePostal: "68130",
    population: 6000,
    distance: 20,
    featuredImage: "/images/villes/altkirch.webp",
    specificites: [
      "Sous-préfecture du Haut-Rhin, chef-lieu d'arrondissement",
      "Capitale du Sundgau alsacien",
      "Architecture de centre-ville préservée",
    ],
    communesAlentours: ["Ferrette", "Hirsingue", "Carspach", "Dannemarie", "Seppois-le-Bas"],
    seoTitle: "Rénovation Altkirch (68130) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison et bâtiment à Altkirch 68130, capitale du Sundgau. Cuisine, salle de bain, peinture, carrelage. Devis gratuit sous 48h.",
  },
  {
    slug: "soultz-haut-rhin",
    name: "Soultz-Haut-Rhin",
    codePostal: "68360",
    population: 7000,
    distance: 28,
    featuredImage: "/images/villes/soultz-haut-rhin.webp",
    specificites: [
      "Ville viticole sur la route des vins d'Alsace",
      "Architecture médiévale préservée",
      "Potentiel rénovation des maisons vigneronnes",
    ],
    communesAlentours: ["Guebwiller", "Issenheim", "Wuenheim", "Jungholtz", "Bollwiller"],
    seoTitle: "Rénovation Soultz-Haut-Rhin (68360) | Artisan Haut-Rhin",
    seoDescription:
      "Rénovation maison viticole et appartement à Soultz-Haut-Rhin 68360. Cuisine, salle de bain, peinture, façade. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "brunstatt-didenheim",
    name: "Brunstatt-Didenheim",
    codePostal: "68350",
    population: 10000,
    distance: 14,
    featuredImage: "/images/villes/brunstatt-didenheim.webp",
    specificites: [
      "Commune résidentielle aisée de la banlieue mulhousienne",
      "Villas et pavillons des années 1970-2000",
      "Clientèle frontalière et cadres",
    ],
    communesAlentours: ["Mulhouse", "Riedisheim", "Rixheim", "Habsheim", "Illzach"],
    seoTitle: "Rénovation Brunstatt-Didenheim (68350) | Artisan Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Brunstatt-Didenheim 68350. Pavillons, cuisines, salles de bain, isolation. Devis gratuit, réponse rapide depuis Mulhouse.",
  },
  {
    slug: "pfastatt",
    name: "Pfastatt",
    codePostal: "68120",
    population: 8000,
    distance: 16,
    featuredImage: "/images/villes/pfastatt.webp",
    specificites: [
      "Commune de l'agglomération mulhousienne",
      "Tissu résidentiel dense, maisons de ville et appartements",
      "Forte demande en rénovation énergétique",
    ],
    communesAlentours: ["Mulhouse", "Wittenheim", "Kingersheim", "Wittelsheim", "Lutterbach"],
    seoTitle: "Rénovation Pfastatt (68120) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Pfastatt 68120, agglomération mulhousienne. Cuisine, salle de bain, isolation, peinture. Devis gratuit.",
  },
  {
    slug: "lutterbach",
    name: "Lutterbach",
    codePostal: "68460",
    population: 5000,
    distance: 15,
    featuredImage: "/images/villes/lutterbach.webp",
    specificites: [
      "Commune de la vallée de la Doller",
      "Tissu résidentiel récent, développement pavillonnaire",
      "Bonne accessibilité vers Mulhouse et Saint-Louis",
    ],
    communesAlentours: ["Mulhouse", "Pfastatt", "Wittelsheim", "Cernay", "Bollwiller"],
    seoTitle: "Rénovation Lutterbach (68460) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Lutterbach 68460. Maisons, appartements. Cuisine, peinture, carrelage, salle de bain. Devis gratuit.",
  },
  {
    slug: "ensisheim",
    name: "Ensisheim",
    codePostal: "68190",
    population: 7000,
    distance: 20,
    featuredImage: "/images/villes/ensisheim.webp",
    specificites: [
      "Ancienne résidence des Habsbourg (hôtel de la Régence)",
      "Développement de zones pavillonnaires récentes",
      "Nœud routier entre Mulhouse, Colmar et le Rhin",
    ],
    communesAlentours: ["Wittenheim", "Baldersheim", "Ottmarsheim", "Munchhouse", "Bollwiller"],
    seoTitle: "Rénovation Ensisheim (68190) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Ensisheim 68190. Maisons, pavillons, isolation. Cuisine, salle de bain, peinture, carrelage. Devis gratuit sous 48h.",
  },
  {
    slug: "bollwiller",
    name: "Bollwiller",
    codePostal: "68540",
    population: 3500,
    distance: 24,
    featuredImage: "/images/villes/bollwiller.webp",
    specificites: [
      "Commune résidentielle du Haut-Rhin",
      "Zone pavillonnaire en développement",
      "Accès rapide vers Mulhouse et Guebwiller",
    ],
    communesAlentours: ["Guebwiller", "Soultz-Haut-Rhin", "Issenheim", "Wittelsheim", "Ensisheim"],
    seoTitle: "Rénovation Bollwiller (68540) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation à Bollwiller 68540. Maisons, appartements. Cuisine, peinture, carrelage, isolation. Artisan Haut-Rhin. Devis gratuit.",
  },
  {
    slug: "rouffach",
    name: "Rouffach",
    codePostal: "68250",
    population: 5000,
    distance: 32,
    featuredImage: "/images/villes/rouffach.webp",
    specificites: [
      "Ville médiévale sur la route des vins d'Alsace",
      "Vignobles grands crus, maisons vigneronnes à rénover",
      "École viticole et architecture remarquable",
    ],
    communesAlentours: ["Pfaffenheim", "Guebwiller", "Westhalten", "Soultzmatt", "Issenheim"],
    seoTitle: "Rénovation Rouffach (68250) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Rénovation maison viticole et appartement à Rouffach 68250. Cuisine, salle de bain, peinture, façade, isolation. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "munster",
    name: "Munster",
    codePostal: "68140",
    population: 5000,
    distance: 55,
    featuredImage: "/images/villes/munster.webp",
    specificites: [
      "Ville de la vallée de Munster, patrimoine naturel vosgien",
      "Fermes vosgiennesà rénover",
      "Tourisme vert, gîtes et chalets",
    ],
    communesAlentours: ["Soultzbach-les-Bains", "Gunsbach", "Vieux-Thann", "Metzeral", "Hachimette"],
    seoTitle: "Rénovation Munster (68140) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Munster 68140, vallée vosgienne. Fermes, chalets, maisons. Isolation, peinture, carrelage, salle de bain. Devis gratuit.",
  },
  {
    slug: "sainte-marie-aux-mines",
    name: "Sainte-Marie-aux-Mines",
    codePostal: "68160",
    population: 5000,
    distance: 80,
    featuredImage: "/images/villes/sainte-marie-aux-mines.webp",
    specificites: [
      "Ville historique des mines d'argent",
      "Architecture Renaissance et maisons alsaciennes",
      "Col de Sainte-Marie — passage entre Alsace et Lorraine",
    ],
    communesAlentours: ["Lièpvre", "Rombach-le-Franc", "Fouchy", "Steige", "Sélestat"],
    seoTitle: "Rénovation Sainte-Marie-aux-Mines (68160) | Artisan Haut-Rhin",
    seoDescription:
      "Rénovation maison alsacienne et bâtiment ancien à Sainte-Marie-aux-Mines 68160. Façade, isolation, peinture, carrelage. Artisan qualifié. Devis gratuit.",
  },
  {
    slug: "orbey",
    name: "Orbey",
    codePostal: "68370",
    population: 4000,
    distance: 60,
    featuredImage: "/images/villes/orbey.webp",
    specificites: [
      "Commune de montagne vosgienne, Lac Blanc et Lac Noir",
      "Chalets et fermes vosgiennesà rénover",
      "Forte activité touristique (gîtes, hôtels)",
    ],
    communesAlentours: ["Lapoutroie", "Kaysersberg-Vignoble", "Le Bonhomme", "Hachimette", "Fréland"],
    seoTitle: "Rénovation Orbey (68370) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Orbey 68370, montagne vosgienne. Chalets, maisons, gîtes. Isolation, peinture, sols, salle de bain. Devis gratuit.",
  },
  {
    slug: "sausheim",
    name: "Sausheim",
    codePostal: "68390",
    population: 4000,
    distance: 16,
    featuredImage: "/images/villes/sausheim.webp",
    specificites: [
      "Commune de l'agglomération mulhousienne, zone industrielle et résidentielle",
      "Pavillons et appartements récents",
      "Bonne desserte vers Mulhouse (5 min)",
    ],
    communesAlentours: ["Mulhouse", "Riedisheim", "Rixheim", "Habsheim", "Illzach"],
    seoTitle: "Rénovation Sausheim (68390) | Artisan AIMAN Haut-Rhin",
    seoDescription:
      "Artisan rénovation à Sausheim 68390. Pavillons, cuisine, salle de bain, peinture, isolation. Devis gratuit.",
  },
  {
    slug: "kaysersberg-vignoble",
    name: "Kaysersberg-Vignoble",
    codePostal: "68240",
    population: 7000,
    distance: 70,
    featuredImage: "/images/villes/kaysersberg-vignoble.webp",
    specificites: [
      "Village médiéval élu Plus Beau Village de France",
      "Maisons à colombages, caves vigneronnes",
      "Fort tourisme culturel, rénovations patrimoniales",
    ],
    communesAlentours: ["Ammerschwihr", "Kientzheim", "Sigolsheim", "Orbey", "Lapoutroie"],
    seoTitle: "Rénovation Kaysersberg-Vignoble (68240) | Artisan Haut-Rhin",
    seoDescription:
      "Rénovation maison à colombages et bâtiment ancien à Kaysersberg-Vignoble 68240. Façade, peinture, salle de bain. Artisan qualifié Haut-Rhin. Devis gratuit.",
  },
];
